CREATE TABLE kb_user (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    kb_username VARCHAR(50) NOT NULL UNIQUE,
    kb_email VARCHAR(50) NOT NULL UNIQUE,
    kb_password VARCHAR(255) NOT NULL,
    deactivated TINYINT(1) NOT NULL DEFAULT 0,
    email_verified TINYINT(1) NOT NULL DEFAULT 0,
    created_when DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed_when DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    deactivated_when DATETIME NULL,
    email_verified_when DATETIME NULL,
    last_login DATETIME NULL
);